# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'measure_Suite.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1923, 1389)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.Main_Frame = QtGui.QFrame(self.centralwidget)
        self.Main_Frame.setEnabled(True)
        self.Main_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Main_Frame.setObjectName(_fromUtf8("Main_Frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Main_Frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Data_Frame = QtGui.QFrame(self.Main_Frame)
        self.Data_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Data_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Data_Frame.setObjectName(_fromUtf8("Data_Frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.Data_Frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Dark_Frame = QtGui.QFrame(self.Data_Frame)
        self.Dark_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Dark_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Dark_Frame.setObjectName(_fromUtf8("Dark_Frame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Dark_Frame)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Dark_TransFrame = QtGui.QFrame(self.Dark_Frame)
        self.Dark_TransFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Dark_TransFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.Dark_TransFrame.setObjectName(_fromUtf8("Dark_TransFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Dark_TransFrame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.Dark_TransFrame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.Dark_Frame1 = QtGui.QFrame(self.Dark_TransFrame)
        self.Dark_Frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Dark_Frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.Dark_Frame1.setObjectName(_fromUtf8("Dark_Frame1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.Dark_Frame1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.Dark_Out_Pos_View = PlotWidget(self.Dark_Frame1)
        self.Dark_Out_Pos_View.setObjectName(_fromUtf8("Dark_Out_Pos_View"))
        self.horizontalLayout_5.addWidget(self.Dark_Out_Pos_View)
        self.Dark_Out_Neg_View = PlotWidget(self.Dark_Frame1)
        self.Dark_Out_Neg_View.setObjectName(_fromUtf8("Dark_Out_Neg_View"))
        self.horizontalLayout_5.addWidget(self.Dark_Out_Neg_View)
        self.verticalLayout_4.addWidget(self.Dark_Frame1)
        self.label_3 = QtGui.QLabel(self.Dark_TransFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.Dark_Frame2 = QtGui.QFrame(self.Dark_TransFrame)
        self.Dark_Frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Dark_Frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.Dark_Frame2.setObjectName(_fromUtf8("Dark_Frame2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.Dark_Frame2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.Dark_Probe_Pos_View = PlotWidget(self.Dark_Frame2)
        self.Dark_Probe_Pos_View.setObjectName(_fromUtf8("Dark_Probe_Pos_View"))
        self.horizontalLayout_3.addWidget(self.Dark_Probe_Pos_View)
        self.Dark_Probe_Neg_View = PlotWidget(self.Dark_Frame2)
        self.Dark_Probe_Neg_View.setObjectName(_fromUtf8("Dark_Probe_Neg_View"))
        self.horizontalLayout_3.addWidget(self.Dark_Probe_Neg_View)
        self.verticalLayout_4.addWidget(self.Dark_Frame2)
        self.verticalLayout_3.addWidget(self.Dark_TransFrame)
        self.label_5 = QtGui.QLabel(self.Dark_Frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.Dark_OutFrame = QtGui.QFrame(self.Dark_Frame)
        self.Dark_OutFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Dark_OutFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.Dark_OutFrame.setObjectName(_fromUtf8("Dark_OutFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.Dark_OutFrame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Dark_Trans_Pos_View = PlotWidget(self.Dark_OutFrame)
        self.Dark_Trans_Pos_View.setObjectName(_fromUtf8("Dark_Trans_Pos_View"))
        self.horizontalLayout_2.addWidget(self.Dark_Trans_Pos_View)
        self.Dark_Trans_Neg_View = PlotWidget(self.Dark_OutFrame)
        self.Dark_Trans_Neg_View.setObjectName(_fromUtf8("Dark_Trans_Neg_View"))
        self.horizontalLayout_2.addWidget(self.Dark_Trans_Neg_View)
        self.verticalLayout_3.addWidget(self.Dark_OutFrame)
        self.horizontalLayout.addWidget(self.Dark_Frame)
        self.Light_Frame = QtGui.QFrame(self.Data_Frame)
        self.Light_Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Light_Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.Light_Frame.setObjectName(_fromUtf8("Light_Frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Light_Frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Light_Frame1 = QtGui.QFrame(self.Light_Frame)
        self.Light_Frame1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Light_Frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.Light_Frame1.setObjectName(_fromUtf8("Light_Frame1"))
        self.gridLayout = QtGui.QGridLayout(self.Light_Frame1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_5 = QtGui.QFrame(self.Light_Frame1)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.Light_Probe_Pos_View = PlotWidget(self.frame_5)
        self.Light_Probe_Pos_View.setObjectName(_fromUtf8("Light_Probe_Pos_View"))
        self.horizontalLayout_8.addWidget(self.Light_Probe_Pos_View)
        self.Light_Probe_Neg_View = PlotWidget(self.frame_5)
        self.Light_Probe_Neg_View.setObjectName(_fromUtf8("Light_Probe_Neg_View"))
        self.horizontalLayout_8.addWidget(self.Light_Probe_Neg_View)
        self.gridLayout.addWidget(self.frame_5, 3, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.Light_Frame1)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.Light_Out_Pos_View = PlotWidget(self.frame_4)
        self.Light_Out_Pos_View.setObjectName(_fromUtf8("Light_Out_Pos_View"))
        self.horizontalLayout_7.addWidget(self.Light_Out_Pos_View)
        self.Light_Out_Neg_View = PlotWidget(self.frame_4)
        self.Light_Out_Neg_View.setObjectName(_fromUtf8("Light_Out_Neg_View"))
        self.horizontalLayout_7.addWidget(self.Light_Out_Neg_View)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.Light_Frame1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.Light_Frame1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.Light_Frame1)
        self.label_6 = QtGui.QLabel(self.Light_Frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_2.addWidget(self.label_6)
        self.Light_Frame2 = QtGui.QFrame(self.Light_Frame)
        self.Light_Frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Light_Frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.Light_Frame2.setObjectName(_fromUtf8("Light_Frame2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.Light_Frame2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.Light_Trans_Pos_View = PlotWidget(self.Light_Frame2)
        self.Light_Trans_Pos_View.setObjectName(_fromUtf8("Light_Trans_Pos_View"))
        self.horizontalLayout_4.addWidget(self.Light_Trans_Pos_View)
        self.Light_Trans_Neg_View = PlotWidget(self.Light_Frame2)
        self.Light_Trans_Neg_View.setObjectName(_fromUtf8("Light_Trans_Neg_View"))
        self.horizontalLayout_4.addWidget(self.Light_Trans_Neg_View)
        self.verticalLayout_2.addWidget(self.Light_Frame2)
        self.horizontalLayout.addWidget(self.Light_Frame)
        self.verticalLayout.addWidget(self.Data_Frame)
        self.frame_8 = QtGui.QFrame(self.Main_Frame)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.frame_10 = QtGui.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnStart = QtGui.QPushButton(self.frame_10)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout_6.addWidget(self.btnStart)
        self.Resume_Scan = QtGui.QPushButton(self.frame_10)
        self.Resume_Scan.setObjectName(_fromUtf8("Resume_Scan"))
        self.horizontalLayout_6.addWidget(self.Resume_Scan)
        self.horizontalLayout_9.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_8)
        self.horizontalLayout_10.addWidget(self.Main_Frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1923, 36))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "OutPut Characterisctics", None))
        self.label_3.setText(_translate("MainWindow", "Probe Voltage", None))
        self.label_5.setText(_translate("MainWindow", "Transfer Characteristics", None))
        self.label_2.setText(_translate("MainWindow", "OutPut Characterisctics", None))
        self.label_4.setText(_translate("MainWindow", "Probe Voltage", None))
        self.label_6.setText(_translate("MainWindow", "Transfer Characteristics", None))
        self.btnStart.setText(_translate("MainWindow", "Start Scan", None))
        self.Resume_Scan.setText(_translate("MainWindow", "Start Light Scan", None))

from pyqtgraph import PlotWidget
