# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_char.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1864, 1108)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 0, 439, 751))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_15 = QtGui.QFrame(self.frame_2)
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_15)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame = QtGui.QFrame(self.frame_15)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_vd0 = QtGui.QLabel(self.frame)
        self.label_vd0.setObjectName(_fromUtf8("label_vd0"))
        self.horizontalLayout.addWidget(self.label_vd0)
        self.lineEdit_Vd0 = QtGui.QLineEdit(self.frame)
        self.lineEdit_Vd0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vd0.setObjectName(_fromUtf8("lineEdit_Vd0"))
        self.horizontalLayout.addWidget(self.lineEdit_Vd0)
        self.unit_vds = QtGui.QLabel(self.frame)
        self.unit_vds.setObjectName(_fromUtf8("unit_vds"))
        self.horizontalLayout.addWidget(self.unit_vds)
        self.verticalLayout_4.addWidget(self.frame)
        self.frame_16 = QtGui.QFrame(self.frame_15)
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.frame_16)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_vdf = QtGui.QLabel(self.frame_16)
        self.label_vdf.setObjectName(_fromUtf8("label_vdf"))
        self.horizontalLayout_11.addWidget(self.label_vdf)
        self.lineEdit_Vdf = QtGui.QLineEdit(self.frame_16)
        self.lineEdit_Vdf.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vdf.setObjectName(_fromUtf8("lineEdit_Vdf"))
        self.horizontalLayout_11.addWidget(self.lineEdit_Vdf)
        self.unit_vds_3 = QtGui.QLabel(self.frame_16)
        self.unit_vds_3.setObjectName(_fromUtf8("unit_vds_3"))
        self.horizontalLayout_11.addWidget(self.unit_vds_3)
        self.verticalLayout_4.addWidget(self.frame_16)
        self.frame_14 = QtGui.QFrame(self.frame_15)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.frame_14)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_vdstep = QtGui.QLabel(self.frame_14)
        self.label_vdstep.setObjectName(_fromUtf8("label_vdstep"))
        self.horizontalLayout_10.addWidget(self.label_vdstep)
        self.lineEdit_Vdstep = QtGui.QLineEdit(self.frame_14)
        self.lineEdit_Vdstep.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vdstep.setObjectName(_fromUtf8("lineEdit_Vdstep"))
        self.horizontalLayout_10.addWidget(self.lineEdit_Vdstep)
        self.unit_vds_2 = QtGui.QLabel(self.frame_14)
        self.unit_vds_2.setObjectName(_fromUtf8("unit_vds_2"))
        self.horizontalLayout_10.addWidget(self.unit_vds_2)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.frame.raise_()
        self.frame_14.raise_()
        self.frame_14.raise_()
        self.frame_16.raise_()
        self.verticalLayout_2.addWidget(self.frame_15)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.frame_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_Vg0 = QtGui.QLabel(self.frame_4)
        self.label_Vg0.setObjectName(_fromUtf8("label_Vg0"))
        self.horizontalLayout_2.addWidget(self.label_Vg0)
        self.lineEdit_Vg0 = QtGui.QLineEdit(self.frame_4)
        self.lineEdit_Vg0.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vg0.setObjectName(_fromUtf8("lineEdit_Vg0"))
        self.horizontalLayout_2.addWidget(self.lineEdit_Vg0)
        self.unit_v0 = QtGui.QLabel(self.frame_4)
        self.unit_v0.setObjectName(_fromUtf8("unit_v0"))
        self.horizontalLayout_2.addWidget(self.unit_v0)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_6 = QtGui.QFrame(self.frame_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_Vgf = QtGui.QLabel(self.frame_6)
        self.label_Vgf.setObjectName(_fromUtf8("label_Vgf"))
        self.horizontalLayout_4.addWidget(self.label_Vgf)
        self.lineEdit_Vgf = QtGui.QLineEdit(self.frame_6)
        self.lineEdit_Vgf.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vgf.setObjectName(_fromUtf8("lineEdit_Vgf"))
        self.horizontalLayout_4.addWidget(self.lineEdit_Vgf)
        self.units_Vgf = QtGui.QLabel(self.frame_6)
        self.units_Vgf.setObjectName(_fromUtf8("units_Vgf"))
        self.horizontalLayout_4.addWidget(self.units_Vgf)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_Vgstep = QtGui.QLabel(self.frame_5)
        self.label_Vgstep.setObjectName(_fromUtf8("label_Vgstep"))
        self.horizontalLayout_3.addWidget(self.label_Vgstep)
        self.lineEdit_Vgstep = QtGui.QLineEdit(self.frame_5)
        self.lineEdit_Vgstep.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_Vgstep.setObjectName(_fromUtf8("lineEdit_Vgstep"))
        self.horizontalLayout_3.addWidget(self.lineEdit_Vgstep)
        self.units_vgset = QtGui.QLabel(self.frame_5)
        self.units_vgset.setObjectName(_fromUtf8("units_vgset"))
        self.horizontalLayout_3.addWidget(self.units_vgset)
        self.verticalLayout.addWidget(self.frame_5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_7 = QtGui.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_scanrate = QtGui.QLabel(self.frame_7)
        self.label_scanrate.setObjectName(_fromUtf8("label_scanrate"))
        self.horizontalLayout_5.addWidget(self.label_scanrate)
        self.lineEdit_rate = QtGui.QLineEdit(self.frame_7)
        self.lineEdit_rate.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_rate.setObjectName(_fromUtf8("lineEdit_rate"))
        self.horizontalLayout_5.addWidget(self.lineEdit_rate)
        self.units_scanrate = QtGui.QLabel(self.frame_7)
        self.units_scanrate.setObjectName(_fromUtf8("units_scanrate"))
        self.horizontalLayout_5.addWidget(self.units_scanrate)
        self.verticalLayout_2.addWidget(self.frame_7)
        self.frame_11 = QtGui.QFrame(self.centralwidget)
        self.frame_11.setGeometry(QtCore.QRect(1490, 10, 351, 581))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.frame_12 = QtGui.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(10, 30, 311, 81))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.frame_12)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.mob_label = QtGui.QLabel(self.frame_12)
        self.mob_label.setObjectName(_fromUtf8("mob_label"))
        self.horizontalLayout_7.addWidget(self.mob_label)
        self.lineEdit_6 = QtGui.QLineEdit(self.frame_12)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.horizontalLayout_7.addWidget(self.lineEdit_6)
        self.label_6 = QtGui.QLabel(self.frame_12)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.frame_13 = QtGui.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(20, 120, 311, 81))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_8 = QtGui.QLabel(self.frame_13)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_7 = QtGui.QLineEdit(self.frame_13)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.horizontalLayout_8.addWidget(self.lineEdit_7)
        self.label_9 = QtGui.QLabel(self.frame_13)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.frame_9 = QtGui.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(480, 10, 1001, 1031))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphicsView_2 = PlotWidget(self.frame_9)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_3.addWidget(self.graphicsView_2)
        self.graphicsView = PlotWidget(self.frame_9)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.frame_8 = QtGui.QFrame(self.frame_9)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.frame_10 = QtGui.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnStart = QtGui.QPushButton(self.frame_10)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.horizontalLayout_6.addWidget(self.btnStart)
        self.btnAbort = QtGui.QPushButton(self.frame_10)
        self.btnAbort.setObjectName(_fromUtf8("btnAbort"))
        self.horizontalLayout_6.addWidget(self.btnAbort)
        self.btnCollect = QtGui.QPushButton(self.frame_10)
        self.btnCollect.setObjectName(_fromUtf8("btnCollect"))
        self.horizontalLayout_6.addWidget(self.btnCollect)
        self.horizontalLayout_9.addWidget(self.frame_10)
        self.verticalLayout_3.addWidget(self.frame_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1864, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_vd0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">ds </span><span style=\" font-size:10pt;\">:</span></p></body></html>", None))
        self.unit_vds.setText(_translate("MainWindow", "V", None))
        self.label_vdf.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">ds </span><span style=\" font-size:10pt;\">:</span></p></body></html>", None))
        self.unit_vds_3.setText(_translate("MainWindow", "V", None))
        self.label_vdstep.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">V</span><span style=\" font-size:10pt; vertical-align:sub;\">ds </span><span style=\" font-size:10pt;\">:</span></p></body></html>", None))
        self.unit_vds_2.setText(_translate("MainWindow", "V", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">V</span><span style=\" font-size:16pt; vertical-align:sub;\">GS</span></p></body></html>", None))
        self.label_Vg0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">0</span><span style=\" font-size:11pt;\">:</span></p></body></html>", None))
        self.unit_v0.setText(_translate("MainWindow", "V", None))
        self.label_Vgf.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">f</span><span style=\" font-size:11pt;\">:</span></p></body></html>", None))
        self.units_Vgf.setText(_translate("MainWindow", "V", None))
        self.label_Vgstep.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">V</span><span style=\" font-size:11pt; vertical-align:sub;\">step</span><span style=\" font-size:11pt;\">:</span></p></body></html>", None))
        self.units_vgset.setText(_translate("MainWindow", "V", None))
        self.label_scanrate.setText(_translate("MainWindow", "Scan Rate", None))
        self.units_scanrate.setText(_translate("MainWindow", "ms", None))
        self.mob_label.setText(_translate("MainWindow", "<html><head/><body><p>U</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.btnStart.setText(_translate("MainWindow", "Start Scan", None))
        self.btnAbort.setText(_translate("MainWindow", "Abort Scan", None))
        self.btnCollect.setText(_translate("MainWindow", "Collect Data", None))

from pyqtgraph import PlotWidget
